
---
name: Code Scanning

on  :
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: 7 12 * * 6

jobs:
  analyze:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        language: [javascript]

    name: Analyze
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analyze
        uses: github/codeql-action/analyze@v1
